### PR TITLE
Split timer when getting remote lock

### PR DESCRIPTION
**Pull request by meggarr**
When the timeout to get a lock is too long and concurrency is high,
it can cause the worker pool starvation. The change here is to split
the timeout into small piece to avoid that.

Signed-off-by: Richard Meng <mengar@qq.com>

Motivation:

When the concurrent locks are many and timeout value is long, it will drain the work pool, especially when the locker consumes too long time.

Conformance:

Your commits should be signed and you should have signed the Eclipse Contributor Agreement as explained in https://github.com/eclipse/vert.x/blob/master/CONTRIBUTING.md
Please also make sure you adhere to the code style guidelines: https://github.com/vert-x3/wiki/wiki/Vert.x-code-style-guidelines

### CODE REVIEW

**Comment by meggarr** [comment]
When this feels good, I will submit the futurized edition for master branch.

**Comment by tsegismont** [comment]
Closing as duplicate of https://github.com/eclipse-vertx/vert.x/issues/3126

**Comment by meggarr** [comment]
@tsegismont #122 is about the release that drains the worker pool, here the change is about *acquire*, would you please check it again?

**Comment by tsegismont** [comment]
@meggarr sorry I did not pay enough attention to the content. Indeed this is not related to #122 .

Why not creating a utility class in your code, that invokes `getLockWithTimeout` with a low value (typically milliseconds) and keeps trying until a max wait time is reached?

This would give other worker tasks a lot of opportunities to get executed while preserving the current behavior (which gives some fairness guarantees).

**Comment by meggarr** [comment]
@tsegismont The change here is just something like you said. But having it as a par of the lib will help other developers as well, some of them may face the same problem. Like me, I spent a whole day to find my performance bug, eventually, I got here.

Anyway, it's your call to have it merged, or keep it mine only.

Thanks~

**Comment by meggarr** [comment]
And, to add to my point, few developer knows that this getLockWithTimeout will block the worker pool..

**Pull request closed without merging**
