### PR TITLE
Add a test to ensure strict round robin strategy for PTP messages

### PR DESCRIPTION
**Pull request by pk-work**
The behavior of the distribution of Point to Point messages when using Hazelcast has changed with Vert.x 4.

Before Point to Point messages were distributed in a strict round-robin fashion. Now it is no longer strict. This is not a real issue, because in the [docs](https://vertx.io/docs/vertx-core/java/#_point_to_point_and_request_response_messaging) only a non-strict fashion is promised, but @vietj asked me to write a reproducer.

### CODE REVIEW

**Comment by vietj** [comment]
even if it is not strict, I think we need to understand the behavior change and check it is not a regression

**Comment by tsegismont** [comment]
There are a couple problems with the test:

- it does not wait for registration to complete before sending
- there is a tiny amount of time after a consumer is registered and before the caches for sending are re-computed

If you change the test like this:

```java
    AtomicInteger cnt1 = new AtomicInteger(), cnt2 = new AtomicInteger();
    startNodes(2);
    vertices[0].eventBus().consumer(ADDRESS1, messgae -> cnt1.incrementAndGet());
    vertices[1].eventBus().consumer(ADDRESS1, messgae -> cnt2.incrementAndGet());
    vertices[0].setTimer(5000, id -> {
      IntStream.range(0, 10).forEach(i -> vertices[0].eventBus().send(ADDRESS1, "wololo"));
      vertices[0].setTimer(2000, id2 -> {
        assertEquals(cnt1.get(), cnt2.get());
        testComplete();
      });
    });
    await();
```

Then it will pass.

Note that the timeouts are exaggerated. In practice the time difference is very short.

**Comment by vietj** [comment]
thanks Thomas

**Comment by pk-work** [comment]
Thanks @tsegismont this makes totally sense. Now, after your explanation, I wonder why I didn't think of it myself :).

**Pull request closed without merging**
