### PR TITLE
Upgraded to Hazelcast 3.8

### LINKED ISSUE #60: Update Hazelcast to 3.7+
We are using some hazelcast 3.7 features in our vert.x based project. If there are no reasons to stay at 3.6, it would be really convenient for us if vert.x used 3.7 or 3.8 itself.

### PR DESCRIPTION
**Pull request by tsegismont**
Fixes #60

### CODE REVIEW

**Comment by tsegismont** [comment]
The build passes on my box. Will wait for 3.4.1 before merging

**Comment by EmadAlblueshi** [comment]
Hi @tsegismont , it will be in 3.4.2 ?

**Comment by tsegismont** [comment]
Yes, if it gets approved

**Comment by cescoffier** [comment]
We need to check if it's compatible with existing clusters, if it requires that all nodes are upgraded, and what we do if it's the case.

**Pull request merged**
