### PR TITLE
Send message right away from worker verticle or inside executeBlocking

### PR DESCRIPTION
**Pull request by tsegismont**
See vert-x3/issues#75

### CODE REVIEW

**Comment by vietj** [comment]
+1 yes

**Comment by gkozyryatskyy** [comment]
Is this already working on version 3.4.1 ?

**Comment by tsegismont** [comment]
@gkozyryatskyy please see #1870 (comment)

It is possible to send messages right away from executeblocking (we have a test for that), but not from a worker verticle.

**Comment by gkozyryatskyy** [comment]
@tsegismont Thank you for your reply! But is there any way to send it from worker (not multithreaded) verticle?

**Comment by tsegismont** [comment]
Please keep the conversation in a single issue :)

2017-05-19 15:35 GMT+02:00 gkozyryatskyy <notifications@github.com>:

**Pull request merged**
