### PR TITLE
Multi map cache performance fix #73

### LINKED ISSUE #73: HazelcastAsyncMultiMap: Near-cache is not used under constant load
This results in poor performance and a hazelcast address lookup on event event-bus message dropping the rate by 10x

The problems seems to come from this commit. The algorithm does not converge. 

https://github.com/vert-x3/vertx-hazelcast/commit/7199d39a0c322b72035bf6ca1c69e7321ebcdc8d

In case of constant concurrent accesses to HazelcastAsync the variable inprogressCount
will never be 0 thus cache will never be used even though there is data in it.

It requires one consumer unregister or register to bring the value to 1 again and then concurrent accesses will keep it high

### PR DESCRIPTION
**Pull request by nolequen**

### CODE REVIEW

**Comment by nolequen** [comment]
Hello, is there any progress here?

**Comment by tsegismont** [comment]
@nolequen thanks for taking some time to look into this.

It is expected that the order is guaranteed per context, not per key.

I sent a PR today which fixes the issue (#77)

**Comment by nolequen** [comment]
@tsegismont thanks for the info about order guarantee. think, I could fix it in my pull request, if it would be useful. should I?

**Comment by tsegismont** [comment]
Thank you but this shouldn't be necessary. I sent another PR with a fix,
waiting for @vietj's review. I'll keep you informed.

2017-07-29 19:09 GMT+02:00 Anton Potsyus <notifications@github.com>:

**Comment by nolequen** [comment]
ok, thanks!

**Comment by tsegismont** [comment]
@nolequen #77 has been merged, thanks for reviewing

**Pull request closed without merging**
