### PR TITLE
New method: AsyncMap::setTtl

### PR DESCRIPTION
**Pull request by ruslansennov**
see eclipse-vertx/vert.x#3537

### CODE REVIEW

**Review by tsegismont — COMMENTED** [review]
Thanks for the update @ruslansennov . What about other cluster managers, have you found similar features in Infinispan, Ignite or Zookeeper?

**Comment by tsegismont** [comment]
>PS. Why InfinispanAsyncMap does not extend AsyncMap?

Because when it's unwrapped it doesn't have the checks for key/value types anymore.

**Comment by ruslansennov** [comment]
Hi @tsegismont 

> What about other cluster managers, have you found similar features in Infinispan, Ignite or Zookeeper?

unfortunately I'm not familiar with these projects close enough

**Comment by tsegismont** [comment]
@ruslansennov I understand but before merging this and backporting to master I would like to know if changing expiration is a generic operation or really specific to Hazelcast.

**Pull request closed without merging**
